-- Reference Tables
-- Generated from database

-- Table: EDS_REFERENCES
DROP TABLE EDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."EDS_REFERENCES"
   (	"EDS_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"EDS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("EDS_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_EDS_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "EDS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: ESK_REFERENCES
DROP TABLE ESK_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."ESK_REFERENCES"
   (	"ESK_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"ESK_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("ESK_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_ESK_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "ESK_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: MDS_REFERENCES
DROP TABLE MDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."MDS_REFERENCES"
   (	"MDS_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"MDS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"AREA" VARCHAR2(100),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("MDS_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_MDS_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "MDS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: PCS_REFERENCES
DROP TABLE PCS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_REFERENCES"
   (	"PCS_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"REVISION_SUFFIX" VARCHAR2(50),
	"RATING_CLASS" VARCHAR2(100),
	"MATERIAL_GROUP" VARCHAR2(100),
	"HISTORICAL_PCS" VARCHAR2(500),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("PCS_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "PCS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: PIPE_ELEMENT_REFERENCES
DROP TABLE PIPE_ELEMENT_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PIPE_ELEMENT_REFERENCES"
   (	"PIPE_ELEMENT_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"ELEMENT_ID" NUMBER NOT NULL ENABLE,
	"ELEMENT_GROUP" VARCHAR2(200),
	"DIMENSION_STANDARD" VARCHAR2(200),
	"PRODUCT_FORM" VARCHAR2(200),
	"MATERIAL_GRADE" VARCHAR2(200),
	"MDS" VARCHAR2(100),
	"MDS_REVISION" VARCHAR2(50),
	"AREA" VARCHAR2(100),
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_PIPE_ELEMENT_REFERENCES" PRIMARY KEY ("PIPE_ELEMENT_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PIPE_ELEMENT_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "ELEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: SC_REFERENCES
DROP TABLE SC_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."SC_REFERENCES"
   (	"SC_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"SC_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("SC_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_SC_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "SC_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_EDS_REFERENCES
DROP TABLE STG_EDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_EDS_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"EDS" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_ESK_REFERENCES
DROP TABLE STG_ESK_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_ESK_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"ESK" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_MDS_REFERENCES
DROP TABLE STG_MDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_MDS_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"MDS" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"Area" VARCHAR2(100),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_PCS_REFERENCES
DROP TABLE STG_PCS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_PCS_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"PCS" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"RevisionSuffix" VARCHAR2(50),
	"RatingClass" VARCHAR2(100),
	"MaterialGroup" VARCHAR2(100),
	"HistoricalPCS" VARCHAR2(500),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_PIPE_ELEMENT_REFERENCES
DROP TABLE STG_PIPE_ELEMENT_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_PIPE_ELEMENT_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"ElementGroup" VARCHAR2(200),
	"DimensionStandard" VARCHAR2(200),
	"ProductForm" VARCHAR2(200),
	"MaterialGrade" VARCHAR2(200),
	"MDS" VARCHAR2(100),
	"MDSRevision" VARCHAR2(50),
	"Area" VARCHAR2(100),
	"ElementID" VARCHAR2(50),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_SC_REFERENCES
DROP TABLE STG_SC_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_SC_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"SC" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_VDS_REFERENCES
DROP TABLE STG_VDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_VDS_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"VDS" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_VSK_REFERENCES
DROP TABLE STG_VSK_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_VSK_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"VSK" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: STG_VSM_REFERENCES
DROP TABLE STG_VSM_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."STG_VSM_REFERENCES"
   (	"PLANT_ID" VARCHAR2(50),
	"ISSUE_REVISION" VARCHAR2(50),
	"VSM" VARCHAR2(100),
	"Revision" VARCHAR2(50),
	"RevDate" VARCHAR2(50),
	"Status" VARCHAR2(50),
	"OfficialRevision" VARCHAR2(50),
	"Delta" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: VDS_REFERENCES
DROP TABLE VDS_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."VDS_REFERENCES"
   (	"VDS_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"VDS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("VDS_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_VDS_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "VDS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: VSK_REFERENCES
DROP TABLE VSK_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."VSK_REFERENCES"
   (	"VSK_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"VSK_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("VSK_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_VSK_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "VSK_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: VSM_REFERENCES
DROP TABLE VSM_REFERENCES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."VSM_REFERENCES"
   (	"VSM_REFERENCES_GUID" RAW(16) DEFAULT SYS_GUID(),
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ISSUE_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"VSM_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"REV_DATE" DATE,
	"STATUS" VARCHAR2(50),
	"OFFICIAL_REVISION" VARCHAR2(50),
	"DELTA" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 PRIMARY KEY ("VSM_REFERENCES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_VSM_REF" UNIQUE ("PLANT_ID", "ISSUE_REVISION", "VSM_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

