-- PCS Detail Tables
-- Generated from database

-- Table: PCS_EMBEDDED_NOTES
DROP TABLE PCS_EMBEDDED_NOTES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_EMBEDDED_NOTES"
   (	"PCS_EMBEDDED_NOTES_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"PCSNAME" VARCHAR2(100),
	"REVISION" VARCHAR2(50),
	"TEXT_SECTION_ID" VARCHAR2(50),
	"TEXT_SECTION_DESCRIPTION" VARCHAR2(500),
	"PAGE_BREAK" VARCHAR2(50),
	"HTML_CLOB" CLOB,
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_EMBEDDED_NOTES" PRIMARY KEY ("PCS_EMBEDDED_NOTES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_EMBEDDED_NOTES" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION", "TEXT_SECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("HTML_CLOB") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
/

-- Table: PCS_HEADER_PROPERTIES
DROP TABLE PCS_HEADER_PROPERTIES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_HEADER_PROPERTIES"
   (	"PCS_HEADER_PROPERTIES_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"PCS" VARCHAR2(100),
	"REVISION" VARCHAR2(50),
	"STATUS" VARCHAR2(50),
	"REV_DATE" DATE,
	"RATING_CLASS" VARCHAR2(100),
	"TEST_PRESSURE" NUMBER(10,2),
	"MATERIAL_GROUP" VARCHAR2(100),
	"DESIGN_CODE" VARCHAR2(100),
	"LAST_UPDATE" DATE,
	"LAST_UPDATE_BY" VARCHAR2(100),
	"APPROVER" VARCHAR2(100),
	"NOTEPAD" CLOB,
	"SC" VARCHAR2(100),
	"VSM" VARCHAR2(100),
	"DESIGN_CODE_REV_MARK" VARCHAR2(50),
	"CORR_ALLOWANCE" NUMBER(10,2),
	"CORR_ALLOWANCE_REV_MARK" VARCHAR2(50),
	"LONG_WELD_EFF" NUMBER(5,2),
	"LONG_WELD_EFF_REV_MARK" VARCHAR2(50),
	"WALL_THK_TOL" VARCHAR2(200),
	"WALL_THK_TOL_REV_MARK" VARCHAR2(50),
	"SERVICE_REMARK" VARCHAR2(500),
	"SERVICE_REMARK_REV_MARK" VARCHAR2(50),
	"DESIGN_PRESS01" NUMBER(10,2),
	"DESIGN_PRESS02" NUMBER(10,2),
	"DESIGN_PRESS03" NUMBER(10,2),
	"DESIGN_PRESS04" NUMBER(10,2),
	"DESIGN_PRESS05" NUMBER(10,2),
	"DESIGN_PRESS06" NUMBER(10,2),
	"DESIGN_PRESS07" NUMBER(10,2),
	"DESIGN_PRESS08" NUMBER(10,2),
	"DESIGN_PRESS09" NUMBER(10,2),
	"DESIGN_PRESS10" NUMBER(10,2),
	"DESIGN_PRESS11" NUMBER(10,2),
	"DESIGN_PRESS12" NUMBER(10,2),
	"DESIGN_PRESS_REV_MARK" VARCHAR2(50),
	"DESIGN_TEMP01" NUMBER(10,2),
	"DESIGN_TEMP02" NUMBER(10,2),
	"DESIGN_TEMP03" NUMBER(10,2),
	"DESIGN_TEMP04" NUMBER(10,2),
	"DESIGN_TEMP05" NUMBER(10,2),
	"DESIGN_TEMP06" NUMBER(10,2),
	"DESIGN_TEMP07" NUMBER(10,2),
	"DESIGN_TEMP08" NUMBER(10,2),
	"DESIGN_TEMP09" NUMBER(10,2),
	"DESIGN_TEMP10" NUMBER(10,2),
	"DESIGN_TEMP11" NUMBER(10,2),
	"DESIGN_TEMP12" NUMBER(10,2),
	"DESIGN_TEMP_REV_MARK" VARCHAR2(50),
	"NOTE_ID_CORR_ALLOWANCE" NUMBER(10,0),
	"NOTE_ID_SERVICE_CODE" NUMBER(10,0),
	"NOTE_ID_WALL_THK_TOL" NUMBER(10,0),
	"NOTE_ID_LONG_WELD_EFF" NUMBER(10,0),
	"NOTE_ID_GENERAL_PCS" NUMBER(10,0),
	"NOTE_ID_DESIGN_CODE" NUMBER(10,0),
	"NOTE_ID_PRESS_TEMP_TABLE" NUMBER(10,0),
	"NOTE_ID_PIPE_SIZE_WTH_TABLE" NUMBER(10,0),
	"PRESS_ELEMENT_CHANGE" VARCHAR2(50),
	"TEMP_ELEMENT_CHANGE" VARCHAR2(50),
	"MATERIAL_GROUP_ID" NUMBER(10,0),
	"SPECIAL_REQ_ID" NUMBER(10,0),
	"SPECIAL_REQ" VARCHAR2(500),
	"NEW_VDS_SECTION" VARCHAR2(100),
	"TUBE_PCS" VARCHAR2(100),
	"EDS_MJ_MATRIX" VARCHAR2(100),
	"MJ_REDUCTION_FACTOR" NUMBER(5,2),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_HEADER_PROPS" PRIMARY KEY ("PCS_HEADER_PROPERTIES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_HEADER" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("NOTEPAD") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
/

-- Table: PCS_PIPE_ELEMENTS
DROP TABLE PCS_PIPE_ELEMENTS CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_PIPE_ELEMENTS"
   (	"PCS_PIPE_ELEMENTS_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"PCS" VARCHAR2(100),
	"REVISION" VARCHAR2(50),
	"MATERIAL_GROUP_ID" NUMBER(10,0),
	"ELEMENT_GROUP_NO" NUMBER(10,0),
	"LINE_NO" NUMBER(10,0),
	"ELEMENT" VARCHAR2(200),
	"DIM_STANDARD" VARCHAR2(100),
	"FROM_SIZE" VARCHAR2(50),
	"TO_SIZE" VARCHAR2(50),
	"PRODUCT_FORM" VARCHAR2(100),
	"MATERIAL" VARCHAR2(200),
	"MDS" VARCHAR2(100),
	"EDS" VARCHAR2(100),
	"EDS_REVISION" VARCHAR2(50),
	"ESK" VARCHAR2(100),
	"REVMARK" VARCHAR2(50),
	"REMARK" VARCHAR2(500),
	"PAGE_BREAK" VARCHAR2(50),
	"ELEMENT_ID" NUMBER(10,0),
	"FREE_TEXT" VARCHAR2(500),
	"NEW_DELETED_LINE" VARCHAR2(50),
	"INITIAL_INFO" VARCHAR2(200),
	"INITIAL_REVMARK" VARCHAR2(50),
	"MDS_VARIANT" VARCHAR2(100),
	"MDS_REVISION" VARCHAR2(50),
	"AREA" VARCHAR2(100),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	"NOTE_ID" VARCHAR2(50),
	 CONSTRAINT "PK_PCS_PIPE_ELEMENTS" PRIMARY KEY ("PCS_PIPE_ELEMENTS_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_PIPE_ELEMENTS" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION", "ELEMENT_GROUP_NO", "LINE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: PCS_PIPE_SIZES
DROP TABLE PCS_PIPE_SIZES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_PIPE_SIZES"
   (	"PCS_PIPE_SIZES_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"PCS" VARCHAR2(100),
	"REVISION" VARCHAR2(50),
	"NOM_SIZE" VARCHAR2(50),
	"OUTER_DIAM" NUMBER(10,2),
	"WALL_THICKNESS" NUMBER(10,3),
	"SCHEDULE" VARCHAR2(50),
	"UNDER_TOLERANCE" NUMBER(10,3),
	"CORROSION_ALLOWANCE" NUMBER(10,3),
	"WELDING_FACTOR" NUMBER(5,3),
	"DIM_ELEMENT_CHANGE" VARCHAR2(50),
	"SCHEDULE_IN_MATRIX" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_PIPE_SIZES" PRIMARY KEY ("PCS_PIPE_SIZES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_PIPE_SIZES" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION", "NOM_SIZE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: PCS_TEMP_PRESSURES
DROP TABLE PCS_TEMP_PRESSURES CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_TEMP_PRESSURES"
   (	"PCS_TEMP_PRESSURES_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"TEMPERATURE" NUMBER(10,2),
	"PRESSURE" NUMBER(10,2),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_TEMP_PRESSURES" PRIMARY KEY ("PCS_TEMP_PRESSURES_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_TEMP_PRESSURES" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION", "TEMPERATURE", "PRESSURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

-- Table: PCS_VALVE_ELEMENTS
DROP TABLE PCS_VALVE_ELEMENTS CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_VALVE_ELEMENTS"
   (	"PCS_VALVE_ELEMENTS_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PCS_REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"VALVE_GROUP_NO" NUMBER(10,0),
	"LINE_NO" NUMBER(10,0),
	"VALVE_TYPE" VARCHAR2(100),
	"VDS" VARCHAR2(100),
	"VALVE_DESCRIPTION" VARCHAR2(500),
	"FROM_SIZE" VARCHAR2(50),
	"TO_SIZE" VARCHAR2(50),
	"REVMARK" VARCHAR2(50),
	"REMARK" VARCHAR2(500),
	"PAGE_BREAK" VARCHAR2(50),
	"NOTE_ID" VARCHAR2(50),
	"PREVIOUS_VDS" VARCHAR2(100),
	"NEW_DELETED_LINE" VARCHAR2(50),
	"INITIAL_INFO" VARCHAR2(200),
	"INITIAL_REVMARK" VARCHAR2(50),
	"SIZE_RANGE" VARCHAR2(100),
	"STATUS" VARCHAR2(50),
	"REVISION" VARCHAR2(50),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_VALVE_ELEMENTS" PRIMARY KEY ("PCS_VALVE_ELEMENTS_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_VALVE_ELEMENTS" UNIQUE ("PLANT_ID", "PCS_NAME", "PCS_REVISION", "VALVE_GROUP_NO", "LINE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

