-- Catalog Tables
-- Generated from database

-- Table: PCS_LIST
DROP TABLE PCS_LIST CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."PCS_LIST"
   (	"PCS_LIST_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"PLANT_ID" VARCHAR2(50) NOT NULL ENABLE,
	"PCS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50) NOT NULL ENABLE,
	"STATUS" VARCHAR2(50),
	"REV_DATE" DATE,
	"RATING_CLASS" VARCHAR2(100),
	"TEST_PRESSURE" NUMBER(10,2),
	"MATERIAL_GROUP" VARCHAR2(100),
	"DESIGN_CODE" VARCHAR2(100),
	"LAST_UPDATE" DATE,
	"LAST_UPDATE_BY" VARCHAR2(100),
	"APPROVER" VARCHAR2(100),
	"NOTEPAD" CLOB,
	"SPECIAL_REQ_ID" NUMBER(10,0),
	"TUBE_PCS" VARCHAR2(100),
	"NEW_VDS_SECTION" VARCHAR2(100),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_PCS_LIST" PRIMARY KEY ("PCS_LIST_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_PCS_LIST" UNIQUE ("PLANT_ID", "PCS_NAME", "REVISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("NOTEPAD") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
/

-- Table: VDS_LIST
DROP TABLE VDS_LIST CASCADE CONSTRAINTS PURGE;
/

  CREATE TABLE "TR2000_STAGING"."VDS_LIST"
   (	"VDS_LIST_GUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
	"VDS_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"REVISION" VARCHAR2(50),
	"STATUS" VARCHAR2(50),
	"REV_DATE" DATE,
	"LAST_UPDATE" DATE,
	"LAST_UPDATE_BY" VARCHAR2(100),
	"DESCRIPTION" VARCHAR2(4000),
	"NOTEPAD" VARCHAR2(4000),
	"SPECIAL_REQ_ID" NUMBER,
	"VALVE_TYPE_ID" NUMBER,
	"RATING_CLASS_ID" NUMBER,
	"MATERIAL_GROUP_ID" NUMBER,
	"END_CONNECTION_ID" NUMBER,
	"BORE_ID" NUMBER,
	"VDS_SIZE_ID" NUMBER,
	"SIZE_RANGE" VARCHAR2(100),
	"CUSTOM_NAME" VARCHAR2(200),
	"SUBSEGMENT_LIST" VARCHAR2(4000),
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"LAST_MODIFIED_DATE" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_VDS_LIST" PRIMARY KEY ("VDS_LIST_GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UK_VDS_LIST_NAME_REV" UNIQUE ("VDS_NAME", "REVISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
/

